// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package swagger

import (
	"github.com/swaggo/swag"
)

type s struct{}

func (s *s) ReadDoc() string {
	return ""
}

func init() {
	swag.Register(swag.Name, &s{})
}
