run:
  timeout: 3m
linters:
  enable:
    - misspell
    - stylecheck
    - gocritic
    - unparam
    - unconvert
    - whitespace
    - makezero
    - gosec
    - bodyclose
    - testifylint
  disable:
    - errcheck
linters-settings:
  gocritic:
    # Which checks should be disabled; can't be combined with 'enabled-checks'; default is empty
    disabled-checks:
      - regexpMust
      - appendAssign
      - exitAfterDefer
      - ifElseChain
  gosec:
    # To specify a set of rules to explicitly exclude.
    # Available rules: https://github.com/securego/gosec#available-rules
    excludes:
      - G402
      - G404
      - G601
  testifylint:
    enable:
      - bool-compare
      - compares
      - empty
      - error-is-as
      - error-nil
      - expected-actual
      - len
      - require-error
      - suite-dont-use-pkg
      - suite-extra-assert-call
