version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - depguard
    - durationcheck
    - exptostd
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - goheader
    - gosec
    - intrange
    - makezero
    - misspell
    - nilnesserr
    - perfsprint
    - protogetter
    - reassign
    - recvcheck
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - whitespace
  settings:
    depguard:
      rules:
        denied-deps:
          deny:
            - pkg: go.uber.org/atomic
              desc: Use 'sync/atomic' instead of 'go.uber.org/atomic'
            - pkg: github.com/pkg/errors
              desc: Use 'github.com/pingcap/errors' instead of 'github.com/pkg/errors'
    errcheck:
      exclude-functions:
        - (*github.com/unrolled/render.Render).JSON
        - (*github.com/unrolled/render.Render).Data
        - (*github.com/unrolled/render.Render).Text
        - (net/http.ResponseWriter).Write
        - github.com/pingcap/log.Sync
        - (github.com/tikv/pd/pkg/ratelimit.Runner).RunTask
    gocritic:
      disabled-checks:
        - regexpMust
        - appendAssign
        - exitAfterDefer
        - ifElseChain
    goheader:
      values:
        regexp:
          COPYRIGHT-HEADER: Copyright \d{4} TiKV Project Authors.
      template: |-
        {{ COPYRIGHT-HEADER }}

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    gosec:
      excludes:
        - G402
        - G404
        - G115
    perfsprint:
      string-format: false
    revive:
      confidence: 0.8
      severity: error
      rules:
        - name: atomic
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: blank-imports
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: confusing-naming
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: confusing-results
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T,*github.com/user/repo/testing.Harness'
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: datarace
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: defer
          arguments:
            - - call-chain
              - loop
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: dot-imports
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: duplicated-imports
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: empty-block
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: empty-lines
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: error-return
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: error-strings
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: error-naming
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: identical-branches
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: if-return
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: modifies-parameter
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: optimize-operands-order
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: range
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: range-val-in-closure
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: range-val-address
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: receiver-naming
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: indent-error-flow
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: superfluous-else
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: unnecessary-stmt
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: unreachable-code
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: unused-receiver
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: useless-break
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: var-naming
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: waitgroup-by-value
          severity: warning
          disabled: false
          exclude:
            - ""
    testifylint:
      enable:
        - blank-import
        - bool-compare
        - compares
        - empty
        - error-is-as
        - error-nil
        - expected-actual
        - formatter
        - len
        - negative-positive
        - require-error
        - suite-dont-use-pkg
        - suite-extra-assert-call
        - suite-subtest-run
        - useless-assert
      disable:
        - float-compare
        - go-require
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: (_test\.go|pkg/mock/.*\.go|tests/.*\.go)
      - linters:
          - errcheck
        path: (pd-analysis|pd-api-bench|pd-backup|pd-ctl|pd-heartbeat-bench|pd-recover|pd-simulator|pd-tso-bench|pd-ut|regions-dump|stores-dump)
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/pingcap)
        - prefix(github.com/tikv/pd)
        - blank
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: interface{}
          replacement: any
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
