// Copyright 2020 TiKV Project Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package uiserver

import (
	"github.com/pingcap/tidb-dashboard/pkg/config"
	"net/http"
	"sync"
)

var (
	once   sync.Once
	assets http.FileSystem
)

// Assets returns the Assets FileSystem of the dashboard UI
// NOTE: if you see "undefined: assets" error, please run `make dashboard-ui` in the root directory of the repository.
func Assets(cfg *config.Config) http.FileSystem {
	once.Do(func() {
		// Placeholder: In production, this should be generated by vfsgen or similar.
		// Here we use a minimal empty dir FS as fallback if assets FS is not generated.
		assets = http.Dir("/dev/null")
	})
	return assets
}
