// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "github.com/tikv/pd/pkg/response"
)

func main() {
  g := gen.NewGenerator("region_easyjson.go")
  g.SetPkg("response", "github.com/tikv/pd/pkg/response")
  g.Add(pkg.EasyJSON_exporter_MetaPeer(nil))
  g.Add(pkg.EasyJSON_exporter_PDPeerStats(nil))
  g.Add(pkg.EasyJSON_exporter_RegionInfo(nil))
  g.Add(pkg.EasyJSON_exporter_RegionsInfo(nil))
  g.Add(pkg.EasyJSON_exporter_ReplicationStatus(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
