// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  response

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( MetaPeer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MetaPeer ) UnmarshalJSON([]byte) error { return nil }
func ( MetaPeer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MetaPeer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MetaPeer *MetaPeer

func ( PDPeerStats ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PDPeerStats ) UnmarshalJSON([]byte) error { return nil }
func ( PDPeerStats ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PDPeerStats ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PDPeerStats *PDPeerStats

func ( RegionInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RegionInfo ) UnmarshalJSON([]byte) error { return nil }
func ( RegionInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RegionInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RegionInfo *RegionInfo

func ( RegionsInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RegionsInfo ) UnmarshalJSON([]byte) error { return nil }
func ( RegionsInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RegionsInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RegionsInfo *RegionsInfo

func ( ReplicationStatus ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ReplicationStatus ) UnmarshalJSON([]byte) error { return nil }
func ( ReplicationStatus ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ReplicationStatus ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ReplicationStatus *ReplicationStatus
