name: PD Tests
on:
  push:
    branches:
      - master
      - release-4.0
      - release-5.*
  pull_request:
    branches:
      - master
      - release-4.0
      - release-5.*
jobs:
  chunks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        worker_id: [1, 2, 3, 4, 5, 6]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            **/.tools
            **/.dashboard_download_cache
          key: ${{ runner.os }}-go-${{ matrix.worker_id }}-${{ hashFiles('**/go.sum') }}
      - name: Make Test
        run: make ci-test-job JOB_COUNT=6 JOB_INDEX=${{ matrix.worker_id }}
