name: PD Test
on:
  push:
    branches:
      - master
      - release-4.0
      - release-5.*
      - release-6.*
      - cherry-pick-8123
  pull_request:
    branches:
      - master
      - release-4.0
      - release-5.*
      - release-6.*
      - cherry-pick-8123
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  chunks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        worker_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    outputs:
      job-total: 10
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            **/.tools
            **/.dashboard_download_cache
          key: ${{ runner.os }}-go-${{ matrix.worker_id }}-${{ hashFiles('**/go.sum') }}
      - name: Make Test
        env:
          WORKER_ID: ${{ matrix.worker_id }}
          WORKER_COUNT: 10
        run: |
          [ $WORKER_ID -ne $WORKER_COUNT ] && make ci-test-job JOB_COUNT=$(($WORKER_COUNT-1)) JOB_INDEX=$WORKER_ID
          [ $WORKER_ID -eq $WORKER_COUNT ] && make ci-test-job-submod
          mv covprofile covprofile_$WORKER_ID
          sed -i "/failpoint_binding/d" covprofile_$WORKER_ID
