name: PD Real TiUP Test
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  real-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            **/.tools
            **/.dashboard_download_cache
          key: ${{ runner.os }}-go-${{ matrix.worker_id }}-${{ hashFiles('**/go.sum') }}

      - name: Test
        run: make check
        working-directory: tests/integrations/realtiup
